### ISSUE TITLE
Q_NAMESPACE error when trying to build

### ISSUE THREAD

**Issue by soccerdude008** [paceholder/nodeeditor#338]
When I try to build this on Windows with msvc I get the following error:

nodeeditor/include/QtNodes/internal/Definitions.hpp(14): Error: Namespace declaration lacks Q_NAMESPACE macro.

Any clue how to fix that error?

**Comment by paceholder** [comment]
Would be not bad to tell what compiler and Qt version you are using

**Comment by paceholder** [comment]
Qt's docs say that  `Q_NAMESPACE_EXPORT` which we have in the file performs the same function as your missing `Q_NAMESPACE`. For the sake of experimenting try to puth `Q_NAMESPACE` right after the namespace definition.

**Comment by soccerdude008** [comment]
I am running on Windows and using Qt 5.9.7 and MSVC 19.34.31935.0 (Visual Studio 17 2022).

I also tried with MinGW CXX compiler as GNU 6.3.0, and got the same error. 

From a quick search for the docs you mention, it looks like Q_NAMESPACE_EXPORT wasn't introduced until Qt 5.14, so that could be my issue. I tried putting Q_NAMESPACE right after the namespace definition, and it threw a bunch more errors, so I'll try installing a newer version of Qt to see if it resolves it!

**Comment by paceholder** [comment]
> Q_NAMESPACE_EXPORT wasn't introduced until Qt 5.14

Oh, I did not notice that. Sorry, I was initially developing just on 6.x and just lately fixed all inconsistencies to compile on the latest 5.15.xx

I think 5.15 is the only and the last supported version from the 5.x release, it makes sense to update your installation.

**Comment by zhoutotong** [comment]
Hi, I got same error, and my env is: Ubuntu 20.04, Qt Ver: 5.12.
and 5.12 is default Qt version in Ubuntu 20.04, would you solved this problem for Qt5.12？

**Comment by paceholder** [comment]
The continuous integratino on https://www.appveyor.com/ builds this project with MSVS and Qt 5.15

**Comment by soccerdude008** [comment]
@paceholder Sorry I haven't had a chance to try downloading Qt 5.15 yet, but totally expect it will work in that case, so feel free to close out the issue. I guess the only thing you might change in the repo is in the README.rst it lists Qt > 5.2 as a dependency, so maybe update that to Qt >= 5.15?

**Comment by paceholder** [comment]
I updated Readme

**Comment by rayment** [comment]
It is definitely worth allowing this project to compile on less than Qt 5.15 because Ubuntu 20.04 LTS uses Qt 5.12.8.

I use this project as a submodule and a CMake pipeline, and it is trivial to fix the problem (at least using the project as a shared libary) by replacing line 16 as follows:

```
diff --git a/include/QtNodes/internal/Definitions.hpp b/include/QtNodes/internal/Definitions.hpp
index ffb9670..5a0866c 100644
--- a/include/QtNodes/internal/Definitions.hpp
+++ b/include/QtNodes/internal/Definitions.hpp
@@ -13,7 +13,7 @@

 namespace QtNodes
 {
-Q_NAMESPACE_EXPORT(NODE_EDITOR_PUBLIC)
+Q_NAMESPACE

 /**
  * Constants used for fetching QVariant data from GraphModel.
```

Can we perhaps wrap this in an `#ifdef` ?

**Comment by rayment** [comment]
Looks like I spoke too soon - I see a commit has already fixed this. My reasoning still stands which makes me happy to see you are taking care of the backward compatibility so thank you!
